=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/xml/activitymgr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT model (durations?, collaborators?, tasks?, contributions?)>

<!ELEMENT durations (duration*)>
<!ELEMENT duration (value, is-active?)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT is-active (#PCDATA)>

<!ELEMENT collaborators (collaborator*)>
<!ELEMENT collaborator (login, first-name, last-name, is-active?)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!-- ELEMENT is-active (#PCDATA) --><!-- élément déjà déclaré pour les durées -->

<!ELEMENT tasks (task*)>
<!ELEMENT task (path, name, budget?, initially-consumed?, todo?, comment?)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT initially-consumed (#PCDATA)>
<!ELEMENT todo (#PCDATA)>
<!ELEMENT comment (#PCDATA)>

<!ELEMENT contributions (contribution*)>
<!ELEMENT contribution (contributor-ref, task-ref)>
<!ATTLIST contribution
	year CDATA #REQUIRED
	month CDATA #REQUIRED
	day CDATA #REQUIRED
	duration CDATA #REQUIRED
>
<!ELEMENT contributor-ref (#PCDATA)>
<!ELEMENT task-ref (#PCDATA)>

=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/xml/XmlTest.CreateDurations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "activitymgr.dtd">
<model>
	<durations>
		<duration>
			<value>200</value>
		</duration>
		<duration>
			<value>300</value>
		</duration>
		<duration>
			<value>400</value>
		</duration>
	</durations>
</model>

=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE node SYSTEM "activitymgr.dtd">
<model>
  <durations>
    <duration>25</duration>
    <duration>50</duration>
    <duration>75</duration>
    <duration>100</duration>
  </durations>
  <collaborators>
    <collaborator>
      <login>login</login>
      <first-name>FirstName</first-name>
      <last-name>LastName</last-name>
    </collaborator>
  </collaborators>
  <tasks>
    <task>
      <path>/Par</path>
      <name>Parent name</name>
      <budget>0</budget>
      <initially-consumed>0</initially-consumed>
      <todo>0</todo>
    </task>
    <task>
      <path>/Par/Code</path>
      <name>Name</name>
      <budget>1</budget>
      <initially-consumed>2</initially-consumed>
      <todo>3</todo>
    </task>
  </tasks>
  <contributions>
    <contribution year="2006" month="1" day="1" duration="25">
      <contributor-ref>login</contributor-ref>
      <task-ref>/Par/Code</task-ref>
    </contribution>
  </contributions>
</model>

=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/report/ReportTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "activitymgr.dtd">
<model>
  <durations>
    <duration><value>25</value><is-active>true</is-active></duration>
    <duration><value>50</value><is-active>true</is-active></duration>
    <duration><value>75</value><is-active>true</is-active></duration>
    <duration><value>100</value><is-active>true</is-active></duration>
  </durations>
  <collaborators>
    <collaborator><login>jdoe</login><first-name>John</first-name><last-name>Doe</last-name><is-active>true</is-active></collaborator>
    <collaborator><login>wsmith</login><first-name>Will</first-name><last-name>Smith</last-name><is-active>true</is-active></collaborator>
  </collaborators>
  <tasks>
    <task><path>/PR</path><name>Projects</name></task>
    <task><path>/PR/PA</path><name>Project A</name></task>
    <task><path>/PR/PA/SPE</path><name>Specification</name><budget>100</budget><initially-consumed>200</initially-consumed><todo>300</todo></task>
    <task><path>/PR/PA/DEV</path><name>Development</name></task>
    <task><path>/PR/PA/DEV/MA</path><name>Module A</name><budget>100</budget><todo>400</todo></task>
    <task><path>/PR/PA/DEV/MB</path><name>Module B</name><budget>400</budget><initially-consumed>300</initially-consumed></task>
    <task><path>/PR/PA/TST</path><name>Test</name></task>
    <task><path>/PR/PB</path><name>Project B</name></task>
    <task><path>/PR/PB/SPE</path><name>Specification</name></task>
    <task><path>/PR/PB/DEV</path><name>Development</name></task>
    <task><path>/PR/PB/DEV/MC</path><name>Module C</name><budget>800</budget><todo>400</todo></task>
    <task><path>/PR/PB/DEV/MD</path><name>Module D</name><initially-consumed>100</initially-consumed></task>
    <task><path>/PR/PB/TST</path><name>Test</name><budget>600</budget></task>
    <task><path>/ABS</path><name>Absence</name></task>
    <task><path>/ABS/VAC</path><name>Vacations</name></task>
    <task><path>/ABS/ILL</path><name>Illness</name></task>
  </tasks>
  <!-- contributions>
    <contribution year="2017" month="1" day="16" duration="25">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/SPE</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="16" duration="25">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/TST</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="16" duration="50">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/DEV/MA</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="17" duration="100">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/DEV/MA</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="18" duration="100">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/DEV/MB</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="19" duration="25">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/DEV/MA</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="19" duration="75">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/PR/PA/TST</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="20" duration="100">
      <contributor-ref>jdoe</contributor-ref>
      <task-ref>/ABS/VAC</task-ref>
    </contribution>

    <contribution year="2017" month="1" day="16" duration="25">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PA/SPE</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="16" duration="25">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/ABS/ILL</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="18" duration="25">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/SPE</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="16" duration="50">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/SPE</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="18" duration="50">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/DEV/MC</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="17" duration="100">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/DEV/MC</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="19" duration="100">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/TST</task-ref>
    </contribution>
    <contribution year="2017" month="1" day="20" duration="100">
      <contributor-ref>wsmith</contributor-ref>
      <task-ref>/PR/PB/TST</task-ref>
    </contribution>
  </contributions -->
</model>

=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/xml/XmlTest.DuplicateCollaboratorLogin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "activitymgr.dtd">
<model>
	<collaborators>
		<collaborator>
			<login>login1</login>
			<first-name>First Name 1</first-name>
			<last-name>Last Name 1</last-name>
		</collaborator>
		<collaborator>
			<login>login1</login>
			<first-name>First Name 2</first-name>
			<last-name>Last Name 2</last-name>
		</collaborator>
	</collaborators>
</model>

=== mPorhel/Activity-Manager/core/tests/org.activitymgr.core.tests/src/org/activitymgr/core/xml/XmlTest.CreateContributions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "activitymgr.dtd">
<model>
	<durations>
		<duration>
			<value>25</value>
		</duration>
		<duration>
			<value>50</value>
		</duration>
		<duration>
			<value>75</value>
		</duration>
		<duration>
			<value>100</value>
		</duration>
	</durations>
	<collaborators>
		<collaborator>
			<login>login1</login>
			<first-name>First Name 1</first-name>
			<last-name>Last Name 1</last-name>
		</collaborator>
		<collaborator>
			<login>login2</login>
			<first-name>First Name 2</first-name>
			<last-name>Last Name 2</last-name>
		</collaborator>
	</collaborators>
	<tasks>
		<task>
			<path>/TASK1</path>
			<name>My task1</name>
		</task>
		<task>
			<path>/TASK2</path>
			<name>My task2</name>
		</task>
	</tasks>
	<contributions>
		<contribution year="2006" month="01" day="01" duration="100">
			<contributor-ref>login1</contributor-ref>
			<task-ref>/TASK1</task-ref>
		</contribution>
		<contribution year="2006" month="01" day="01" duration="75">
			<contributor-ref>login2</contributor-ref>
			<task-ref>/TASK2</task-ref>
		</contribution>
	</contributions>
</model>
